app/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("hx-list/", views.AccountList.as_view(), name="hx-list"),
    path("create/", views.AccountCreate.as_view(), name="create"),
    path("<pk>/", views.AccountDetails.as_view(), name="details"),
    path("<pk>/update/", views.AccountUpdate.as_view(), name="update"),
    path("<pk>/delete/", views.AccountDelete.as_view(), name="delete"),
]

app/app/urls.py
# noqa: D413
from django.contrib import admin
from django.urls import include, path

from . import views

handler404 = views.my_404

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("favicon.ico", views.favicon, name="favicon"),
    path("empty/", views.empty, name="empty"),  # HTMX endpoint to delete elements
    path("", views.landing, name="landing"),
    path("ledgers/", include("ledgers.urls")),
    path("entries/", include("entries.urls")),
    path("accounts/", include("accounts.urls")),
    path("journals/", include("journals.urls")),
]

app/entries/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("hx-list/", views.EntryList.as_view(), name="hx-list"),
    path("create/", views.EntryCreate.as_view(), name="create"),
    path("<pk>/", views.EntryDetails.as_view(), name="details"),
    path("<pk>/update/", views.EntryUpdate.as_view(), name="update"),
    path("<pk>/delete/", views.EntryDelete.as_view(), name="delete"),
    path("hx-rows-by-entry/<pk>/", views.EntryRowByEntry.as_view(), name="hx-entry_rows"),
    path("hx-rows-by-ledger/<pk>/", views.EntryRowByLedger.as_view(), name="hx-ledger_rows"),
    path("hx-rows-by-account/<pk>/", views.EntryRowByAccount.as_view(), name="hx-account_rows"),
    path("hx-rows-by-journal/<pk>/", views.EntryByJournal.as_view(), name="hx-journal_rows"),
]

app/accounts/models.py
from django.db import models


# Create your models here.
class Account(models.Model):
    id = models.CharField(max_length=16, primary_key=True, blank=False)  # Search name
    name = models.CharField(max_length=50, blank=False)  # Display name
    is_creditor = models.BooleanField(blank=False, choices=[(False, "Debtor"), (True, "Creditor")])
    notes = models.TextField(blank=True)

    def __str__(self):
        return str(self.id)

app/accounts/forms.py
from django import forms

from .models import Account


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["id", "name", "is_creditor", "notes"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Render widgets with Bootstrap styling
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

        # Smaller text for Notes
        self.fields["notes"].widget.attrs["class"] += " form-control-sm"

    def clean_id(self):
        pk = self.cleaned_data["id"]

        if pk in ["create", "hx-list"]:
            error_msg = "That ID is a reserved name"
            raise forms.ValidationError(error_msg, code="pk-reserved-name")

        return pk

app/accounts/views.py
import logging

from typing import TYPE_CHECKING

from django.contrib import messages
from django.db.models import ProtectedError
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

if TYPE_CHECKING:
    from entries.models import EntryRow

from .forms import AccountForm
from .models import Account

logger = logging.getLogger("django")


# Create your views here.
def overview(request):
    return render(request, "accounts/overview.html")


class AccountDetails(generic.DetailView):
    model = Account
    template_name = "accounts/details.html"


class AccountList(generic.ListView):
    model = Account
    template_name = "accounts/content/accounts_list.html"
    ordering = "id"


class AccountCreate(generic.CreateView):
    model = Account
    template_name = "accounts/create_update.html"
    success_url = reverse_lazy("accounts:overview")
    form_class = AccountForm


class AccountUpdate(generic.UpdateView):
    model = Account
    template_name = "accounts/create_update.html"
    success_url = reverse_lazy("accounts:overview")
    form_class = AccountForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class AccountDelete(generic.DeleteView):
    model = Account
    template_name = "accounts/delete.html"
    success_url = reverse_lazy("accounts:overview")

    def post(self, request, *args, **kwargs):
        try:
            super().post(request, *args, **kwargs)
        except ProtectedError as err:
            messages.error(request, "Account has rows and thus cannot be deleted.")

            context = self.get_context_data(**kwargs)
            protected_objects: set[EntryRow] = err.protected_objects  # type: ignore reportGeneralTypeIssues

            context["protected_objects"] = {row.entry for row in protected_objects}
            logger.info("%s", context["protected_objects"])
            return self.render_to_response(context)

        return redirect(self.get_success_url())

app/accounts/templates/accounts/_base.html
{% extends "_base.html" %}

{% block bg-color %} var(--account-bg-color) {% endblock bg-color %}

{% block title %} Accounts {% endblock title %}

app/accounts/templates/accounts/create_update.html
{% extends "accounts/_base.html" %}

{% block page-title %}
{% if is_update %}
Update Account: {{ account.id }}
{% else %}
Create new Account
{% endif %}
{% endblock page-title %}

{% block navbar-extra %}
{% if is_update %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-account" href="{% url 'accounts:details' account %}">
  <span class="nav-link-title">
    Details
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-account" href="{% url 'accounts:delete' account %}">
  <span class="nav-link-title">
    Delete
  </span>
  </a>
</li>
{% endif %}
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    {% if not is_update %}
    <div class="card col-2">
      <div class="card-body">ID</div>
    </div>
    {% endif %}
    <div class="card col-3">
      <div class="card-body">Name</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Type</div>
    </div>
    {% if is_update %}
    <div class="card col-6">
    {% else %}
    <div class="card col-4">
    {% endif %}
      <div class="card-body">Notes</div>
    </div>
  </div>

  {% if is_update %}
  <form action="{% url 'accounts:update' account %}" method="post">
  {% else %}
  <form action="{% url 'accounts:create' %}" method="post">
  {% endif %}
  {% csrf_token %}
  {{ form.non_field_errors }}
    <div class="row row-cards mb-1 justify-content-around">
      {% if is_update %}
      {{ form.id.errors }}
      <div class="card col-2 h-100" hidden>
        <div class="card-body">
          {{ form.id }}
        </div>
      </div>
      {% else %}
      <div class="card col-2 h-100">
        <div class="card-body">
          {{ form.id }}
          {{ form.id.errors }}
        </div>
      </div>
      {% endif %}

      <div class="card col-3 h-100">
        <div class="card-body">
          {{ form.name }}
          {{ form.name.errors }}
        </div>
      </div>
      <div class="card col-2 h-100">
        <div class="card-body">
          {{ form.is_creditor }}
          {{ form.is_creditor.errors }}
        </div>
      </div>
      {% if is_update %}
      <div class="card col-6">
      {% else %}
      <div class="card col-4">
      {% endif %}
        <div class="card-body">
          {{ form.notes }}
          {{ form.notes.errors }}
        </div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      {% if is_update %}
      <div class="col-9"></div>
      <div class="col-1"></div>
      {% else %}
      <div class="col-8"></div>
      <div class="col-1"></div>
      <div class="col-1"></div>
      {% endif %}

      <div class="card col-1">
        {% if is_update %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Update!"/>
        {% else %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Create!"/>
        {% endif %}
      </div>
    </div>
  </form>
</div>
{% endblock content %}

app/accounts/templates/accounts/delete.html
{% extends "accounts/_base.html" %}

{% load static %}

{% block page-title %} Delete Account: {{ account }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-account" href="{% url 'accounts:details' account %}">
  <span class="nav-link-title">
    Details
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-account" href="{% url 'accounts:update' account %}">
  <span class="nav-link-title">
    Update
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <form action="{% url 'accounts:delete' account %}" method="post">
    {% csrf_token %}
    <div class="row row-cards mb-1 justify-content-around strong">
      <div class="card col-3">
        <div class="card-body">Name</div>
      </div>
      <div class="card col-2">
        <div class="card-body">Type</div>
      </div>
      <div class="card col-6">
        <div class="card-body">Notes</div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      <div class="card col-3">
        <div class="card-body">{{ account.name }}</div>
      </div>
      <div class="card col-2">
        <div class="card-body">
          {% if account.is_creditor %}
          <span class="badge bg-red-lt">Creditor</span>
          {% else %}
          <span class="badge bg-lime-lt">Debtor</span>
          {% endif %}
        </div>
      </div>
      <div class="card col-6">
        <div class="card-body">{{ account.notes | default:'<em>No notes.</em>' }}</div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      <div class="col-7"></div>
      <div class="col-1"></div>

      <div class="card col-3">
        <div class="card-body">
          <div class="input-group">
            <span class="input-group-text">
              <input class="form-check-input" type="checkbox" title="Confirm deletion." required/>
            </span>
            <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Delete!"/>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<div class="container mt-4">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-1">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Date</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Ledger</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Account</div>
    </div>
    <div class="card col-4">
      <div class="card-body">Document</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Value</div>
    </div>
  </div>

  <div id="entry_rows_placeholder"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
    hx-get="{% url 'entries:hx-account_rows' account.id %}">
  </div>
</div>
{% endblock content %}

app/accounts/templates/accounts/details.html
{% extends "accounts/_base.html" %}

{% block page-title %} Account: {{ account.id }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-account" href="{% url 'accounts:update' account %}">
  <span class="nav-link-title">
    Update
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-account" href="{% url 'accounts:delete' account %}">
  <span class="nav-link-title">
    Delete
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-3">
      <div class="card-body">Name</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Type</div>
    </div>
    <div class="card col-6">
      <div class="card-body">Notes</div>
    </div>
  </div>
  <div class="row row-cards mb-1 justify-content-around">
    <div class="card col-3">
      <div class="card-body">{{ account.name }}</div>
    </div>
    <div class="card col-2">
      <div class="card-body">
        {% if account.is_creditor %}
        <span class="badge bg-red-lt">Creditor</span>
        {% else %}
        <span class="badge bg-lime-lt">Debtor</span>
        {% endif %}
      </div>
    </div>
    <div class="card col-6">
      <div class="card-body">{{ account.notes | default:'<em>No notes.</em>' }}</div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-1">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Date</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Ledger</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Account</div>
    </div>
    <div class="card col-4">
      <div class="card-body">Document</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Value</div>
    </div>
  </div>

  <div id="entry_rows_placeholder"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
    hx-get="{% url 'entries:hx-account_rows' account.id %}">
  </div>
</div>
{% endblock content %}

app/accounts/templates/accounts/overview.html
{% extends "accounts/_base.html" %}

{% block page-title %} Overview of Accounts {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-account" href="{% url 'accounts:create' %}">
  <span class="nav-link-title">
    Create
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-2">
      <div class="card-body">ID</div>
    </div>
    <div class="card col-3">
      <div class="card-body">Name</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Type</div>
    </div>
    <div class="card col-4">
      <div class="card-body">Notes</div>
    </div>
  </div>

  <div id="account_rows_placeholder"
    hx-target="this"
    hx-swap="outerHTML"
    hx-get="{% url 'accounts:hx-list' %}"
    hx-trigger="load">
  </div>
</div>
{% endblock content %}