app/app/urls.py
# noqa: D413
from django.contrib import admin
from django.urls import include, path

from . import views

handler404 = views.my_404

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("favicon.ico", views.favicon, name="favicon"),
    path("empty/", views.empty, name="empty"),  # HTMX endpoint to delete elements
    path("", views.landing, name="landing"),
    path("ledgers/", include("ledgers.urls")),
    path("entries/", include("entries.urls")),
    path("accounts/", include("accounts.urls")),
    path("journals/", include("journals.urls")),
]

app/entries/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("hx-list/", views.EntryList.as_view(), name="hx-list"),
    path("create/", views.EntryCreate.as_view(), name="create"),
    path("<pk>/", views.EntryDetails.as_view(), name="details"),
    path("<pk>/update/", views.EntryUpdate.as_view(), name="update"),
    path("<pk>/delete/", views.EntryDelete.as_view(), name="delete"),
    path("hx-rows-by-entry/<pk>/", views.EntryRowByEntry.as_view(), name="hx-entry_rows"),
    path("hx-rows-by-ledger/<pk>/", views.EntryRowByLedger.as_view(), name="hx-ledger_rows"),
    path("hx-rows-by-account/<pk>/", views.EntryRowByAccount.as_view(), name="hx-account_rows"),
    path("hx-rows-by-journal/<pk>/", views.EntryByJournal.as_view(), name="hx-journal_rows"),
]

app/journals/urls.py
from django.urls import path

from . import views

app_name = "journals"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("hx-list/", views.JournalList.as_view(), name="hx-list"),
    path("create/", views.JournalCreate.as_view(), name="create"),
    path("<pk>/", views.JournalDetails.as_view(), name="details"),
    path("<pk>/update/", views.JournalUpdate.as_view(), name="update"),
    path("<pk>/delete/", views.JournalDelete.as_view(), name="delete"),
]

app/journals/models.py
from django.db import models


# Create your models here.
class Journal(models.Model):
    id = models.CharField(max_length=16, primary_key=True, blank=False)  # Search name
    name = models.CharField(max_length=50, blank=False)  # Display name
    type = models.CharField(
        max_length=3,
        blank=False,
        choices=[
            ("INC", "Income"),
            ("EXP", "Expense"),
            ("CAS", "Cash"),
            ("GEN", "General"),
        ],
    )
    notes = models.TextField(blank=True)

    def __str__(self):
        return str(self.id)

app/journals/forms.py
from django import forms

from .models import Journal


class JournalForm(forms.ModelForm):
    class Meta:
        model = Journal
        fields = ["id", "name", "type", "notes"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Render widgets with Bootstrap styling
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

        # Smaller text for Notes
        self.fields["notes"].widget.attrs["class"] += " form-control-sm"

    def clean_id(self):
        pk = self.cleaned_data["id"]

        if pk in ["create", "hx-list"]:
            error_msg = "That ID is a reserved name"
            raise forms.ValidationError(error_msg, code="pk-reserved-name")

        return pk

app/journals/views.py
from django.contrib import messages
from django.db.models import ProtectedError
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

from .forms import JournalForm
from .models import Journal


# Create your views here.
def overview(request):
    return render(request, "journals/overview.html")


class JournalDetails(generic.DetailView):
    model = Journal
    template_name = "journals/details.html"


class JournalList(generic.ListView):
    model = Journal
    template_name = "journals/content/list.html"
    ordering = "id"


class JournalCreate(generic.CreateView):
    model = Journal
    template_name = "journals/create_update.html"
    success_url = reverse_lazy("journals:overview")
    form_class = JournalForm


class JournalUpdate(generic.UpdateView):
    model = Journal
    template_name = "journals/create_update.html"
    success_url = reverse_lazy("journals:overview")
    form_class = JournalForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class JournalDelete(generic.DeleteView):
    model = Journal
    template_name = "journals/delete.html"
    success_url = reverse_lazy("journals:overview")

    def post(self, request, *args, **kwargs):
        try:
            super().post(request, *args, **kwargs)
        except ProtectedError as err:
            messages.error(request, "Journal has entries and thus cannot be deleted.")

            context = self.get_context_data(**kwargs)
            context["protected_objects"] = err.protected_objects
            return self.render_to_response(context)

        return redirect(self.get_success_url())

app/journals/templates/journals/_base.html
{% extends "_base.html" %}

{% block bg-color %} var(--journal-bg-color) {% endblock bg-color %}

{% block title %} Journals {% endblock title %}

app/journals/templates/journals/create_update.html
{% extends "journals/_base.html" %}

{% block page-title %}
{% if is_update %}
Update Journal: {{ journal.id }}
{% else %}
Create new Journal
{% endif %}
{% endblock page-title %}

{% block navbar-extra %}
{% if is_update %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-journal" href="{% url 'journals:details' journal %}">
  <span class="nav-link-title">
    Details
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-journal" href="{% url 'journals:delete' journal %}">
  <span class="nav-link-title">
    Delete
  </span>
  </a>
</li>
{% endif %}
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    {% if not is_update %}
    <div class="card col-2">
      <div class="card-body">ID</div>
    </div>
    {% endif %}
    <div class="card col-3">
      <div class="card-body">Name</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Type</div>
    </div>
    {% if is_update %}
    <div class="card col-6">
    {% else %}
    <div class="card col-4">
    {% endif %}
      <div class="card-body">Notes</div>
    </div>
  </div>

  {% if is_update %}
  <form action="{% url 'journals:update' journal %}" method="post">
  {% else %}
  <form action="{% url 'journals:create' %}" method="post">
  {% endif %}
    {% csrf_token %}
    <div class="row row-cards mb-1 justify-content-around">
      {% if is_update %}
      {{ form.id.errors }}
      <div class="card col-2 h-100" hidden>
        <div class="card-body">
          {{ form.id }}
        </div>
      </div>
      {% else %}
      <div class="card col-2 h-100">
        <div class="card-body">
          {{ form.id }}
          {{ form.id.errors }}
        </div>
      </div>
      {% endif %}

      <div class="card col-3 h-100">
        <div class="card-body">
          {{ form.name }}
          {{ form.name.errors }}
        </div>
      </div>
      <div class="card col-2 h-100">
        <div class="card-body">
          {{ form.type }}
          {{ form.type.errors }}
        </div>
      </div>
      {% if is_update %}
      <div class="card col-6">
      {% else %}
      <div class="card col-4">
      {% endif %}
        <div class="card-body">
          {{ form.notes }}
          {{ form.notes.errors }}
        </div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      {% if is_update %}
      <div class="col-9"></div>
      <div class="col-1"></div>
      {% else %}
      <div class="col-8"></div>
      <div class="col-1"></div>
      <div class="col-1"></div>
      {% endif %}

      <div class="card col-1">
        {% if is_update %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Update!"/>
        {% else %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Create!"/>
        {% endif %}
      </div>
    </div>
  </form>
</div>
{% endblock content %}

app/journals/templates/journals/delete.html
{% extends "journals/_base.html" %}

{% load static %}

{% block page-title %} Delete Journal: {{ journal }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-journal" href="{% url 'journals:details' journal %}">
  <span class="nav-link-title">
    Details
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-journal" href="{% url 'journals:update' journal %}">
  <span class="nav-link-title">
    Update
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container mb-3">
  <form action="{% url 'journals:delete' journal %}" method="post">
    {% csrf_token %}
    <div class="row row-cards mb-1 justify-content-around strong">
      <div class="card col-3">
        <div class="card-body">Name</div>
      </div>
      <div class="card col-2">
        <div class="card-body">Type</div>
      </div>
      <div class="card col-6">
        <div class="card-body">Notes</div>
      </div>
    </div>
    <div class="row row-cards mb-1 justify-content-around">
      <div class="card col-3">
        <div class="card-body">{{ journal.name }}</div>
      </div>
      <div class="card col-2">
        <div class="card-body">{{ journal.type }}</div>
      </div>
      <div class="card col-6">
        <div class="card-body">{{ journal.notes | default:'<em>No notes.</em>' }}</div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      <div class="col-7"></div>
      <div class="col-1"></div>

      <div class="card col-3">
        <div class="card-body">
          <div class="input-group">
            <span class="input-group-text">
              <input class="form-check-input" type="checkbox" title="Confirm deletion." required/>
            </span>
            <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Delete!"/>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-2">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Journal</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Number of rows</div>
    </div>
    <div class="card col-5">
      <div class="card-body">Notes</div>
    </div>
  </div>

  <div id="entry_rows_placeholder"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
    hx-get="{% url 'entries:hx-journal_rows' journal.id %}">
  </div>
</div>
{% endblock content %}

app/journals/templates/journals/details.html
{% extends "journals/_base.html" %}

{% block page-title %} Journal: {{ journal.id }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-journal" href="{% url 'journals:update' journal %}">
  <span class="nav-link-title">
    Update
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-journal" href="{% url 'journals:delete' journal %}">
  <span class="nav-link-title">
    Delete
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-3">
      <div class="card-body">Name</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Type</div>
    </div>
    <div class="card col-6">
      <div class="card-body">Notes</div>
    </div>
  </div>
  <div class="row row-cards mb-1 justify-content-around">
    <div class="card col-3">
      <div class="card-body">{{ journal.name }}</div>
    </div>
    <div class="card col-2">
      <div class="card-body">{{ journal.type }}</div>
    </div>
    <div class="card col-6">
      <div class="card-body">{{ journal.notes }}</div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-2">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Journal</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Number of rows</div>
    </div>
    <div class="card col-5">
      <div class="card-body">Notes</div>
    </div>
  </div>

  <div id="entry_rows_placeholder"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
    hx-get="{% url 'entries:hx-journal_rows' journal.id %}">
  </div>
</div>
{% endblock content %}

app/journals/templates/journals/overview.html
{% extends "journals/_base.html" %}

{% block page-title %} Overview of Journals {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-journal" href="{% url 'journals:create' %}">
  <span class="nav-link-title">
    Create
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="col-xl-2 col-4 card">
      <div class="card-body">ID</div>
    </div>
    <div class="col-xl-3 col-7 card">
      <div class="card-body">Name</div>
    </div>
    <div class="col-xl-2 col-4 card">
      <div class="card-body">Type</div>
    </div>
    <div class="col-xl-4 col-7 card">
      <div class="card-body">Notes</div>
    </div>
  </div>

  <div id="journals_list_placeholder"
    hx-get="{% url 'journals:hx-list' %}"
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML">
  </div>
</div>
{% endblock content %}