app/app/urls.py
# noqa: D413
from django.contrib import admin
from django.urls import include, path

from . import views

handler404 = views.my_404

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("favicon.ico", views.favicon, name="favicon"),
    path("empty/", views.empty, name="empty"),  # HTMX endpoint to delete elements
    path("", views.landing, name="landing"),
    path("ledgers/", include("ledgers.urls")),
    path("entries/", include("entries.urls")),
    path("accounts/", include("accounts.urls")),
    path("journals/", include("journals.urls")),
]

app/entries/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("hx-list/", views.EntryList.as_view(), name="hx-list"),
    path("create/", views.EntryCreate.as_view(), name="create"),
    path("<pk>/", views.EntryDetails.as_view(), name="details"),
    path("<pk>/update/", views.EntryUpdate.as_view(), name="update"),
    path("<pk>/delete/", views.EntryDelete.as_view(), name="delete"),
    path("hx-rows-by-entry/<pk>/", views.EntryRowByEntry.as_view(), name="hx-entry_rows"),
    path("hx-rows-by-ledger/<pk>/", views.EntryRowByLedger.as_view(), name="hx-ledger_rows"),
    path("hx-rows-by-account/<pk>/", views.EntryRowByAccount.as_view(), name="hx-account_rows"),
    path("hx-rows-by-journal/<pk>/", views.EntryByJournal.as_view(), name="hx-journal_rows"),
]

app/ledgers/urls.py
from django.urls import path

from . import views

app_name = "ledgers"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("hx-list/", views.LedgersList.as_view(), name="hx-list"),
    path("create/", views.LedgerCreate.as_view(), name="create"),
    path("<pk>/", views.LedgerDetails.as_view(), name="details"),
    path("<pk>/update/", views.LedgerUpdate.as_view(), name="update"),
    path("<pk>/delete/", views.LedgerDelete.as_view(), name="delete"),
]

app/ledgers/models.py
from django.db import models


# Create your models here.
class Ledger(models.Model):
    id = models.CharField(max_length=16, primary_key=True, blank=False)  # Search name
    name = models.CharField(max_length=50, blank=False)  # Display name
    type = models.CharField(
        max_length=3,
        blank=False,
        choices=[
            ("INC", "Income"),
            ("EXP", "Expenses"),
            ("ASS", "Assets"),
            ("EQU", "Equity"),
            ("LIA", "Liabilities"),
        ],
    )
    notes = models.TextField(blank=True)

    entryrow_set: models.Manager

    def __str__(self):
        return str(self.id)

    def calculate_sum(self):
        return self.entryrow_set.aggregate(sum=models.Sum("value"))["sum"]

app/ledgers/forms.py
from django import forms

from .models import Ledger


class LedgerForm(forms.ModelForm):
    class Meta:
        model = Ledger
        fields = ["id", "name", "type", "notes"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Render widgets with Bootstrap styling
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

        # Smaller text for Notes
        self.fields["notes"].widget.attrs["class"] += " form-control-sm"

    def clean_id(self):
        pk = self.cleaned_data["id"]

        if pk in ["create", "hx-list"]:
            error_msg = "That ID is a reserved name"
            raise forms.ValidationError(error_msg, code="pk-reserved-name")

        return pk

app/ledgers/views.py
import logging
from typing import TYPE_CHECKING

from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy

from django.db.models import ProtectedError
from django.contrib import messages

from .models import Ledger
from .forms import LedgerForm

if TYPE_CHECKING:
    from entries.models import EntryRow

logger = logging.getLogger("django")


# Create your views here.
def overview(request):
    return render(request, "ledgers/overview.html")


class LedgerDetails(generic.DetailView):
    model = Ledger
    template_name = "ledgers/details.html"


class LedgerCreate(generic.CreateView):
    model = Ledger
    template_name = "ledgers/create_update.html"
    success_url = reverse_lazy("ledgers:overview")
    form_class = LedgerForm


class LedgerUpdate(generic.UpdateView):
    model = Ledger
    template_name = "ledgers/create_update.html"
    success_url = reverse_lazy("ledgers:overview")
    form_class = LedgerForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class LedgerDelete(generic.DeleteView):
    model = Ledger
    template_name = "ledgers/delete.html"
    success_url = reverse_lazy("ledgers:overview")

    def post(self, request, *args, **kwargs):
        try:
            super().post(request, *args, **kwargs)
        except ProtectedError as err:
            messages.error(request, "Ledger has rows and thus cannot be deleted.")

            context = self.get_context_data(**kwargs)

            protected_objects: set[EntryRow] = err.protected_objects  # type: ignore reportGeneralTypeIssues
            context["protected_objects"] = {row.entry for row in protected_objects}
            return self.render_to_response(context)

        return redirect(self.get_success_url())


# HTMX endpoints
class LedgersList(generic.ListView):
    model = Ledger
    template_name = "ledgers/content/ledger_list.html"
    ordering = "id"

    def get_queryset(self):
        """Return first 50 Ledgers."""
        return Ledger.objects.all()[:50]

app/ledgers/templates/ledgers/_base.html
{% extends "_base.html" %}

{% block bg-color %} var(--ledger-bg-color) {% endblock bg-color %}

{% block title %} Ledgers {% endblock title %}

app/ledgers/templates/ledgers/base.html
{% extends "base.html" %}

{% block title %} Ledgers {% endblock title %}

{% block content %}
<div id="ledger-htmx-target" class="border-0 margin-0 m-0 p-0">
    {% block htmx-shell %} {% endblock htmx-shell %}
</div>
{% endblock content %}

app/ledgers/templates/ledgers/create_update.html
{% extends "ledgers/_base.html" %}

{% block page-title %}
{% if is_update %}
Update Ledger: {{ ledger.id }}
{% else %}
Create new Ledger
{% endif %}
{% endblock page-title %}

{% block navbar-extra %}
{% if is_update %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-ledger" href="{% url 'ledgers:details' ledger %}">
  <span class="nav-link-title">
    Details
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-ledger" href="{% url 'ledgers:delete' ledger %}">
  <span class="nav-link-title">
    Delete
  </span>
  </a>
</li>
{% endif %}
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    {% if not is_update %}
    <div class="card col-2">
      <div class="card-body">ID</div>
    </div>
    {% endif %}
    <div class="card col-3">
      <div class="card-body">Name</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Type</div>
    </div>
    {% if is_update %}
    <div class="card col-6">
    {% else %}
    <div class="card col-4">
    {% endif %}
      <div class="card-body">Notes</div>
    </div>
  </div>

  {% if is_update %}
  <form action="{% url 'ledgers:update' ledger %}" method="post">
  {% else %}
  <form action="{% url 'ledgers:create' %}" method="post">

  {% endif %}
  {% csrf_token %}
  {{ form.non_field_errors }}
    <div class="row row-cards mb-1 justify-content-around">
      {% if is_update %}
      {{ form.id.errors }}
      <div class="card col-2 h-100" hidden>
        <div class="card-body">
          {{ form.id }}
        </div>
      </div>
      {% else %}
      <div class="card col-2 h-100">
        <div class="card-body">
          {{ form.id }}
          {{ form.id.errors }}
        </div>
      </div>
      {% endif %}

      <div class="card col-3 h-100">
        <div class="card-body">
          {{ form.name }}
          {{ form.name.errors }}
        </div>
      </div>
      <div class="card col-2 h-100">
        <div class="card-body">
          {{ form.type }}
          {{ form.type.errors }}
        </div>
      </div>
      {% if is_update %}
      <div class="card col-6">
      {% else %}
      <div class="card col-4">
      {% endif %}
        <div class="card-body">
          {{ form.notes }}
          {{ form.notes.errors }}
        </div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      {% if is_update %}
      <div class="col-9"></div>
      <div class="col-1"></div>
      {% else %}
      <div class="col-8"></div>
      <div class="col-1"></div>
      <div class="col-1"></div>
      {% endif %}

      <div class="card col-1">
        {% if is_update %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Update!"/>
        {% else %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Create!"/>
        {% endif %}
      </div>
    </div>
  </form>
</div>
{% endblock content %}

app/ledgers/templates/ledgers/delete.html
{% extends "ledgers/_base.html" %}

{% load static %}

{% block page-title %} Delete Ledger: {{ ledger }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-ledger" href="{% url 'ledgers:details' ledger %}">
    <span class="nav-link-title">
      Details
    </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-ledger" href="{% url 'ledgers:update' ledger %}">
    <span class="nav-link-title">
      Update
    </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container mb-3">
  <form action="{% url 'ledgers:delete' ledger %}" method="post">
    {% csrf_token %}
    <div class="row row-cards mb-1 justify-content-around strong">
      <div class="card col-3">
        <div class="card-body">Name</div>
      </div>
      <div class="card col-2">
        <div class="card-body">Type</div>
      </div>
      <div class="card col-6">
        <div class="card-body">Notes</div>
      </div>
    </div>
    <div class="row row-cards mb-1 justify-content-around">
      <div class="card col-3">
        <div class="card-body">{{ ledger.name }}</div>
      </div>
      <div class="card col-2">
        <div class="card-body">{{ ledger.type }}</div>
      </div>
      <div class="card col-6">
        <div class="card-body">{{ ledger.notes | default:'<em>No notes.</em>' }}</div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      <div class="col-7"></div>
      <div class="col-1"></div>

      <div class="card col-3">
        <div class="card-body">
          <div class="input-group">
            <span class="input-group-text">
              <input class="form-check-input" type="checkbox" title="Confirm deletion." required/>
            </span>
            <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Delete!"/>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-1">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Date</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Ledger</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Account</div>
    </div>
    <div class="card col-4">
      <div class="card-body">Document</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Value</div>
    </div>
  </div>

  <div id="entry_row_placeholder" hx-target="this" hx-swap="outerHTML" hx-trigger="load"
    hx-get="{% url 'entries:hx-ledger_rows' ledger.id %}">
  </div>

  <div class="row row-cards justify-content-around strong">
    {% comment %} Hidden rows for alignment {% endcomment %}
    <div class="col-5"></div>
    <div class="col-1"></div>
    <div class="col-1"></div>
    <div class="col-1"></div>
    <div class="col-1"></div>

    <div class="card col-2 ml-auto">
      <div class="card-body">€ {{ ledger.calculate_sum | default:0 | floatformat:2 }}</div>
    </div>
  </div>
</div>
{% endblock content %}

app/ledgers/templates/ledgers/details.html
{% extends "ledgers/_base.html" %}

{% block page-title %} Ledger: {{ ledger.id }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-ledger" href="{% url 'ledgers:update' ledger %}">
    <span class="nav-link-title">
      Update
    </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-ledger" href="{% url 'ledgers:delete' ledger %}">
    <span class="nav-link-title">
      Delete
    </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row justify-content-around">
    <div class="col-1">
      <button class="btn">
        Reconcile
      </button>
    </div>
    <div class="vr" style="padding: 0px"></div>
    <div class="col-10">
      <div class="row row-cards mb-1 justify-content-around strong">
        <div class="card col-3">
          <div class="card-body">Name</div>
        </div>
        <div class="card col-2">
          <div class="card-body">Type</div>
        </div>
        <div class="card col-6">
          <div class="card-body">Notes</div>
        </div>
      </div>
      <div class="row row-cards mb-1 justify-content-around">
        <div class="card col-3">
          <div class="card-body">{{ ledger.name }}</div>
        </div>
        <div class="card col-2">
          <div class="card-body">{{ ledger.type }}</div>
        </div>
        <div class="card col-6">
          <div class="card-body">{{ ledger.notes | default:'<em>No notes.</em>' }}</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-1">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Date</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Ledger</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Account</div>
    </div>
    <div class="card col-4">
      <div class="card-body">Document</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Value</div>
    </div>
  </div>

  <div id="entry_row_placeholder" hx-target="this" hx-swap="outerHTML" hx-trigger="load"
    hx-get="{% url 'entries:hx-ledger_rows' ledger.id %}">
  </div>

  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="col-2"></div>
    <div class="col-1"></div>
    <div class="col-1"></div>
    <div class="col-1"></div>
    <div class="col-4"></div>
    <div class="card col-2 ml-auto">
      <div class="card-body">€ {{ ledger.calculate_sum | default:0 | floatformat:2 }}</div>
    </div>
  </div>
</div>
{% endblock content %}

app/ledgers/templates/ledgers/overview.html
{% extends "ledgers/_base.html" %}

{% load static %}

{% block page-title %} Overview of Ledgers {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-ledger" href="{% url 'ledgers:create' %}">
  <span class="nav-link-title">
    Create
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="col-xl-2 col-4 card">
      <div class="card-body">ID</div>
    </div>
    <div class="col-xl-3 col-7 card">
      <div class="card-body">Name</div>
    </div>
    <div class="col-xl-2 col-4 card">
      <div class="card-body">Type</div>
    </div>
    <div class="col-xl-4 col-7 card">
      <div class="card-body">Notes</div>
    </div>
  </div>

  <div id="ledgers_list_placeholder"
    hx-get="{% url 'ledgers:hx-list' %}"
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML">
  </div>
</div>
{% endblock content %}

app/ledgers/templates/ledgers/view.html
<!--
    - [ ] ListView van regels op GBK
    - [ ] Dan met filter opties
    - [ ] En GBK-specifieke gegevens/instellingen (dropdown menu ofzo?)
-->

{% extends "ledgers/_base.html" %}

{% block page-title %} Ledger: {{ ledger.id }} {% endblock %}

{% block htmx-shell %}
<div class="container-xl">
    <div class="row row-cards mb-1 column-gap-1">
        <div class="card card-body col-2 strong">ID</div>
        <div class="card card-body col-4 strong">Name</div>
        <div class="card card-body col-1 strong">Type</div>
        <div class="card card-body col-4 strong">Notes</div>
    </div>
    <div class="row row-cards column-gap-1">
        <div class="card card-body col-2">{{ object.id }}</div>
        <div class="card card-body col-4">{{ object.name }}</div>
        <div class="card card-body col-1">{{ object.type }}</div>
        <div class="card card-body col-4">{{ object.notes }}</div>
    </div>
</div>

<div class="container-xl mt-4"
    hx-target="#entry_row_placeholder"
    hx-swap="outerHTML"
    hx-trigger="load"
    hx-get="{% url 'entries:ledger_rows' ledger.id %}"
>
    <div class="row column-gap-1 strong mb-2 justify-content-around">
        <div class="card col-2">
            <div class="card-body">Date</div>
        </div>
        <div class="card col-2">
            <div class="card-body">Entry</div>
        </div>
        <div class="card col-5">
            <div class="card-body">Document</div>
        </div>
        <div class="card col-2">
            <div class="card-body">Value</div>
        </div>
    </div>

    <div id="entry_row_placeholder">
    </div>

    <div class="row column-gap-1 strong mt-2 justify-content-around">
        <div class="col-2"></div>
        <div class="col-2"></div>
        <div class="col-5"></div>
        <div class="card col-2 ml-auto">
            <div class="card-body">{{ ledger_sum }}</div>
        </div>
    </div>
</div>
{% endblock htmx-shell %}