app/app/urls.py
# noqa: D413
from django.contrib import admin
from django.urls import include, path

from . import views

handler404 = views.my_404

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("favicon.ico", views.favicon, name="favicon"),
    path("empty/", views.empty, name="empty"),  # HTMX endpoint to delete elements
    path("", views.landing, name="landing"),
    path("ledgers/", include("ledgers.urls")),
    path("entries/", include("entries.urls")),
    path("accounts/", include("accounts.urls")),
    path("journals/", include("journals.urls")),
]

app/entries/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("hx-list/", views.EntryList.as_view(), name="hx-list"),
    path("create/", views.EntryCreate.as_view(), name="create"),
    path("<pk>/", views.EntryDetails.as_view(), name="details"),
    path("<pk>/update/", views.EntryUpdate.as_view(), name="update"),
    path("<pk>/delete/", views.EntryDelete.as_view(), name="delete"),
    path("hx-rows-by-entry/<pk>/", views.EntryRowByEntry.as_view(), name="hx-entry_rows"),
    path("hx-rows-by-ledger/<pk>/", views.EntryRowByLedger.as_view(), name="hx-ledger_rows"),
    path("hx-rows-by-account/<pk>/", views.EntryRowByAccount.as_view(), name="hx-account_rows"),
    path("hx-rows-by-journal/<pk>/", views.EntryByJournal.as_view(), name="hx-journal_rows"),
]

app/entries/models.py
import datetime

from django.db import models

from app.settings import upload_path


# Create your models here.
class Entry(models.Model):
    journal = models.ForeignKey("journals.Journal", on_delete=models.PROTECT, blank=False)
    notes = models.TextField(blank=True)

    def __str__(self):
        return str(self.pk)


class EntryRow(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE, blank=False)
    date = models.DateField(blank=False, default=datetime.date.today)
    ledger = models.ForeignKey("ledgers.Ledger", on_delete=models.PROTECT, blank=False)
    account = models.ForeignKey("accounts.Account", on_delete=models.PROTECT, null=True, blank=True)
    document = models.FileField(upload_to=upload_path, blank=True)
    value = models.DecimalField(max_digits=99, decimal_places=2, blank=False)
    reconciled = models.BooleanField(default=False)

    def __str__(self):
        return str(self.pk)

app/entries/forms.py
import logging

from django import forms
from django.forms import (
    BaseInlineFormSet,
    BaseModelFormSet,
    ValidationError,
    inlineformset_factory,
    modelformset_factory,
)

from .models import Entry, EntryRow

logger = logging.getLogger("django")


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["journal", "notes"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Render widgets with Bootstrap styling
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

        # Smaller text for Notes
        self.fields["notes"].widget.attrs["class"] += " form-control-sm"


class EntryRowForm(forms.ModelForm):
    class Meta:
        model = EntryRow
        # Excludes "entry" field
        fields = ["date", "ledger", "account", "document", "value"]
        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Render widgets with Bootstrap styling
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"


class BaseEntryRowFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for entryrow_form in self.forms:
            # Force non-edited rows to still be validated
            entryrow_form.empty_permitted = True

            # Render the HTML required attribute
            entryrow_form.use_required_attribute = True

    def clean(self):
        super().clean()
        if any(self.errors):
            return

        sum_of_values = 0

        for entryrow_form in self.forms:
            if entryrow_form.empty_permitted and not entryrow_form.has_changed():
                continue

            if self.can_delete and self._should_delete_form(entryrow_form):  # type: ignore reportGeneralTypeIssues
                continue

            sum_of_values += entryrow_form.cleaned_data["value"]

        if sum_of_values != 0:
            error_msg = "The rows in this entry don't sum to € 0,-. (sum = € %(sum)s)"
            raise ValidationError(
                error_msg,
                params={"sum": sum_of_values},
                code="nonzero-sum",
            )


class InlineEntryRowFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for entryrow_form in self.forms:
            # Force non-edited rows to still be validated
            # so that the clean method below works
            entryrow_form.empty_permitted = False

            # Render the HTML required attribute
            entryrow_form.use_required_attribute = True

    def clean(self):
        super().clean()
        if any(self.errors):
            return

        sum_of_values = 0

        for entryrow_form in self.forms:
            if entryrow_form.empty_permitted and not entryrow_form.has_changed():
                continue

            if self.can_delete and self._should_delete_form(entryrow_form):  # type: ignore reportGeneralTypeIssues
                continue

            sum_of_values += entryrow_form.cleaned_data["value"]

        if sum_of_values != 0:
            error_msg = "The rows in this entry don't sum to € 0,-. (sum = € %(sum)s)"
            raise ValidationError(
                error_msg,
                params={"sum": sum_of_values},
                code="nonzero-sum",
            )


EntryRowFormSet = modelformset_factory(EntryRow, form=EntryRowForm, formset=BaseEntryRowFormSet)
EntryRowUpdateFormSet = inlineformset_factory(
    Entry,
    EntryRow,
    form=EntryRowForm,
    formset=InlineEntryRowFormSet,
    can_delete=True,
    extra=0,
)

app/entries/views.py
import logging

from django.db.models import Count
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

from .forms import EntryForm, EntryRowFormSet, EntryRowUpdateFormSet
from .models import Entry, EntryRow

logger = logging.getLogger("django")


# Create your views here.
def overview(request):
    return render(request, "entries/overview.html")


class EntryDetails(generic.DetailView):
    model = Entry
    template_name = "entries/details.html"


class EntryList(generic.ListView):
    model = Entry
    template_name = "entries/content/entry_list.html"
    ordering = "id"

    # Annotate entries with num_rows
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["entry_list"] = self.get_queryset().annotate(num_rows=Count("entryrow"))
        return context


class EntryCreate(generic.CreateView):
    model = Entry
    template_name = "entries/create_update.html"
    form_class = EntryForm

    def get_success_url(self):
        return reverse_lazy("entries:overview")

    def post(self, request, *args, **kwargs):  # noqa: ARG002
        self.object = None

        entry_form = EntryForm(request.POST)
        entryrow_formset = EntryRowFormSet(request.POST)

        if entry_form.is_valid() and entryrow_formset.is_valid():
            entry = entry_form.save()

            entryrow_instances = entryrow_formset.save(commit=False)

            for instance in entryrow_instances:
                instance.entry = entry
                instance.save()

            return redirect(self.get_success_url())

        return self.form_invalid(entry_form, entryrow_formset)

    def form_invalid(self, entry_form, entryrow_formset):
        context = self.get_context_data(form=entry_form, entryrow_formset=entryrow_formset)

        return self.render_to_response(context)

    def get_context_data(self, entryrow_formset=None, **kwargs):
        kwargs["is_update"] = False

        if entryrow_formset:
            kwargs["entryrow_formset"] = entryrow_formset
        else:
            kwargs["entryrow_formset"] = EntryRowFormSet(queryset=EntryRow.objects.none())

        return super().get_context_data(**kwargs)


class EntryUpdate(generic.UpdateView):
    model = Entry
    template_name = "entries/create_update.html"
    form_class = EntryForm

    def get_success_url(self):
        return reverse_lazy("entries:details", kwargs={"pk": self.object.pk})

    def post(self, request, *args, **kwargs):  # noqa: ARG002
        self.object = self.get_object()

        entry_form = EntryForm(request.POST, instance=self.object)
        entryrow_formset = EntryRowUpdateFormSet(request.POST, instance=self.object)

        if entry_form.is_valid() and entryrow_formset.is_valid():
            entry_form.save()
            entryrow_formset.save()

            return redirect(self.get_success_url())

        return self.form_invalid(entry_form, entryrow_formset)

    def form_invalid(self, entry_form, entryrow_formset):
        context = self.get_context_data(form=entry_form, entryrow_formset=entryrow_formset)

        return self.render_to_response(context)

    def get_context_data(self, entryrow_formset=None, **kwargs):
        kwargs["is_update"] = True

        if entryrow_formset:
            kwargs["entryrow_formset"] = entryrow_formset
        else:
            kwargs["entryrow_formset"] = EntryRowUpdateFormSet(instance=self.object)

        return super().get_context_data(**kwargs)


class EntryDelete(generic.DeleteView):
    model = Entry
    template_name = "entries/delete.html"
    success_url = reverse_lazy("entries:overview")


# HTMX endpoints
class EntryRowByLedger(generic.ListView):
    model = EntryRow
    template_name = "entries/content/entryrow_list.html"
    context_object_name = "entry_row_list"
    ordering = "id"

    def get_queryset(self):
        return EntryRow.objects.filter(ledger=self.kwargs["pk"])


class EntryRowByEntry(generic.ListView):
    model = EntryRow
    template_name = "entries/content/entryrow_list.html"
    context_object_name = "entry_row_list"
    ordering = "id"

    def get_queryset(self):
        return EntryRow.objects.filter(entry=self.kwargs["pk"])


class EntryRowByAccount(generic.ListView):
    model = EntryRow
    template_name = "entries/content/entryrow_list.html"
    context_object_name = "entry_row_list"
    ordering = "id"

    def get_queryset(self):
        return EntryRow.objects.filter(account=self.kwargs["pk"])


class EntryByJournal(generic.ListView):
    model = Entry
    template_name = "entries/content/entry_list.html"
    ordering = "id"

    # Annotate entries with num_rows
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["entry_list"] = self.get_queryset().annotate(num_rows=Count("entryrow"))
        return context

    def get_queryset(self):
        return Entry.objects.filter(journal=self.kwargs["pk"])

app/entries/templates/entries/_base.html
{% extends "_base.html" %}

{% block bg-color %} var(--entry-bg-color) {% endblock bg-color %}

{% block title %} Entries {% endblock title %}

app/entries/templates/entries/create_update.html
{% extends "entries/_base.html" %}

{% load static %}

{% block page-title %}
{% if is_update %}
Update Entry: {{ entry.id }}
{% else %}
Create new Entry
{% endif %}
{% endblock page-title %}

{% block navbar-extra %}
{% if is_update %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-entry" href="{% url 'entries:details' entry %}">
  <span class="nav-link-title">
    Details
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-entry" href="{% url 'entries:delete' entry %}">
  <span class="nav-link-title">
    Delete
  </span>
  </a>
</li>
{% endif %}
{% endblock navbar-extra %}

{% block content %}
<script>
  var index = {{ entryrow_formset | length }};
  var prefix = "{{ entryrow_formset.prefix }}";

  function add_row(source_index) {
    // Copy value of `index` to a local variable so it stays fixed
    var current_index = index;

    var source_form = document.getElementById("form_entryrow-" + source_index);

    // Update form
    var new_form = source_form.cloneNode(true);
    new_form.id = "form_entryrow-" + current_index;
    new_form.dataset.index = current_index;
    new_form.querySelectorAll("input, select").forEach((element) => element.value = "");
    new_form.querySelector("div.date input").value = source_form.querySelector("div.date input").value;

    // Update buttons
    var delete_button = new_form.querySelector(".delete-button");
    delete_button.onclick = function() { delete_row(current_index); };
    delete_button.disabled = false;

    var add_button = new_form.querySelector(".add-button");
    add_button.onclick = function() { add_row(current_index) };

    // Update form elements
    new_form.querySelector(".id input").setAttribute("name", prefix + "-" + current_index + "-id");
    new_form.querySelector(".id input").setAttribute("id", "id_" + prefix + "-" + current_index + "-id");
    new_form.querySelector(".delete input").setAttribute("name", prefix + "-" + current_index + "-DELETE");
    new_form.querySelector(".delete input").setAttribute("id", "id_" + prefix + "-" + current_index + "-DELETE");
    // Needed because cloneNode causes the `value` attribute to be set to none which breaks functionality,
    // as if the attribute doesn't exist, the default value is 'on' (in Chrome anyways)
    new_form.querySelector(".delete input").removeAttribute("value");
    new_form.querySelector(".date input").setAttribute("name", prefix + "-" + current_index + "-date");
    new_form.querySelector(".date input").setAttribute("id", "id_" + prefix + "-" + current_index + "-date");
    new_form.querySelector(".ledger select").setAttribute("name", prefix + "-" + current_index + "-ledger");
    new_form.querySelector(".ledger select").setAttribute("id", "id_" + prefix + "-" + current_index + "-ledger");
    new_form.querySelector(".account select").setAttribute("name", prefix + "-" + current_index + "-account");
    new_form.querySelector(".account select").setAttribute("id", "id_" + prefix + "-" + current_index + "-account");
    new_form.querySelector(".document input").setAttribute("name", prefix + "-" + current_index + "-document");
    new_form.querySelector(".document input").setAttribute("id", "id_" + prefix + "-" + current_index + "-document");
    new_form.querySelector(".value input").setAttribute("name", prefix + "-" + current_index + "-value");
    new_form.querySelector(".value input").setAttribute("id", "id_" + prefix + "-" + current_index + "-value");

    // Insert into DOM
    source_form.insertAdjacentElement("afterend", new_form);

    var divider = document.querySelector(".divider.d-none").cloneNode();
    divider.classList.remove("d-none");
    divider.classList.add("d-xl-none");
    new_form.insertAdjacentElement("beforebegin", divider);

    // Update management form
    var total_forms_element = document.getElementById("id_" + prefix + "-TOTAL_FORMS");
    var number_of_rows = document.querySelectorAll(".form_entryrow").length;
    total_forms_element.setAttribute("value", number_of_rows);

    index++;
  }

  // Only add a new row if tab was pressed on the final input on the page
  function tab_pressed(event) {
    if (event.key === "Tab") {
      var forms = Array.from(document.querySelectorAll("#entryrow_container .form_entryrow")).filter(
        (element) => !element.hidden
      )
      var last_form = forms[forms.length - 1];
      if (event.srcElement == last_form.querySelector(".value input")) {
        add_row(last_form.dataset.index);
      }
    }
  }

  function delete_row(index) {
    if (!(index === 0)) {
      var row = document.getElementById("form_entryrow-" + index)
      row.classList.remove("fade-in");
      row.classList.add("fade-out");
      setTimeout(() => {
        row.hidden = true;
        // Delete divider
        row.previousElementSibling.remove();

        {% if entryrow_formset.can_delete %}
        row.querySelector(".delete input").checked = true;
        row.querySelectorAll("input, select").forEach((element) => element.required = false);
        {% else %}
        // Make form empty (default values) so that Django filters it
        row.querySelectorAll("input, select").forEach((element) => {
          element.value = "";
          element.required = false;
        });
        {% endif %}
      }, 150);
    } else {
      console.log("Why are you trying to hack the site >:(")
    }
  }
</script>

{{ form.non_field_errors }}
{{ form.non_form_errors }}
{% if is_update %}
<form id="form" action="{% url 'entries:update' entry %}" method="post">
{% else %}
<form id="form" action="{% url 'entries:create' %}" method="post">
{% endif %}
{% csrf_token %}
  <div class="container mb-3">
    <div class="row row-cards mb-1 justify-content-around strong">
      <div class="card col-2">
        <div class="card-body">Journal</div>
      </div>
      <div class="card col-6">
        <div class="card-body">Notes</div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      <div class="card col-2 h-100">
        <div class="card-body">
          {{ form.journal }}
          {{ form.journal.errors }}
        </div>
      </div>
      <div class="card col-6">
        <div class="card-body">
          {{ form.notes }}
          {{ form.notes.errors }}
        </div>
      </div>
    </div>
  </div>

  <div class="container" id="entryrow_container">
    <div class="row row-cards mb-1 justify-content-around sticky-top strong">
      <div class="col-1"></div>

      <div class="card col-5 col-xl-2 date">
        <div class="card-body">Date</div>
      </div>
      <div class="card col-3 col-xl-1 ledger">
        <div class="card-body">Ledger</div>
      </div>
      <div class="card col-3 col-xl-1 account">
        <div class="card-body">Account</div>
      </div>
      <div class="card col-6 col-xl-4 document">
        <div class="card-body">Document</div>
      </div>
      <div class="card col-6 col-xl-2 value">
        <div class="card-body">Value</div>
      </div>
    </div>

    {{ entryrow_formset.non_form_errors }}
    {{ entryrow_formset.management_form }}
    {% for form in entryrow_formset %}
    <div class="form_entryrow fade-in slide" id="form_entryrow-{{ forloop.counter0 }}"
    data-index="{{ forloop.counter0 }}" {% if form.DELETE.value %} hidden {% endif %}>
      <div class="row row-cards mb-1 justify-content-around">
        <div class="card col-1 col-xl-1">
          <div class="card-body">
            <div class="row justify-content-around">
              <button class="btn btn-ghost-cyan p-0 rounded-circle delete-button" type="button"
              style="width: 25px; height: 25px;"
              tabindex="-1"
              {% if forloop.counter0 == 0 %} disabled {% endif %}
              onclick="delete_row({{ forloop.counter0 }})"
              >
                <img src="{% static 'media/feather/x-circle.svg' %}"
                width="20px" height="20px" alt="Circle with X inside"/>
              </button>

              <button class="btn btn-ghost-cyan p-0 rounded-circle add-button" type="button"
              style="width: 25px; height: 25px;"
              tabindex="-1"
              onclick="add_row({{ forloop.counter0 }})"
              >
                <img src="{% static 'media/feather/plus-circle.svg' %}"
                width="20px" height="20px" alt="Circle with X inside"/>
              </button>
            </div>
          </div>
        </div>

        {{ form.non_field_errors }}
        {{ form.id.errors }}
        <div hidden class="id">
          {{ form.id }}
        </div>
        <div hidden class="delete">
          {% if entryrow_formset.can_delete %} {{ form.DELETE }}
          {% else %} <input/> {% comment %} Placeholder to make the JS not error out in the create view {% endcomment %}
          {% endif %}
        </div>
        <div class="card col-5 col-xl-2 date">
          <div class="card-body">
            {{ form.date }}
            {{ form.date.errors }}
          </div>
        </div>
        <div class="card col-3 col-xl-1 ledger">
          <div class="card-body">
            {{ form.ledger }}
            {{ form.ledger.errors }}
          </div>
        </div>
        <div class="card col-3 col-xl-1 account">
          <div class="card-body">
            {{ form.account }}
            {{ form.account.errors }}
          </div>
        </div>
        <div class="card col-6 col-xl-4 document">
          <div class="card-body">
            {{ form.document }}
            {{ form.document.errors }}
          </div>
        </div>
        <div class="card col-6 col-xl-2 value"
        onkeydown="tab_pressed(event)"
        >
          <div class="card-body">
            {{ form.value }}
            {{ form.value.errors }}
          </div>
        </div>
      </div>
    </div>
    {% if not forloop.last %}
    <hr class="divider d-xl-none"/>
    {% endif %}
    {% endfor %}
    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      <div class="col-6"></div>
      <div class="col-1"></div>
      <div class="col-1"></div>
      <div class="col-1"></div>
      <div class="col-1"></div>

      <div class="card col-1">
        {% if is_update %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Update!"/>
        {% else %}
        <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Create!"/>
        {% endif %}
      </div>
    </div>

    {% comment %} Hidden hr so that we can copy it {% endcomment %}
    <hr class="divider d-none"/>
  </div>
</form>
{% endblock content %}

app/entries/templates/entries/delete.html
{% extends "entries/_base.html" %}

{% block page-title %} Delete Entry: {{ entry }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-entry" href="{% url 'entries:details' entry %}">
  <span class="nav-link-title">
    Details
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-entry" href="{% url 'entries:update' entry %}">
  <span class="nav-link-title">
    Update
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<form action="{% url 'entries:delete' entry %}" method="post">
  {% csrf_token %}
  <div class="container mb-3">
    <div class="row row-cards mb-1 justify-content-around strong">
      <div class="card col-2">
        <div class="card-body">Journal</div>
      </div>
      <div class="card col-6">
        <div class="card-body">Notes</div>
      </div>
    </div>
    <div class="row row-cards mb-1 justify-content-around">
      <div class="card col-2">
        <div class="card-body">{{ entry.journal.id }}</div>
      </div>
      <div class="card col-6">
        <div class="card-body">{{ entry.notes | default:'<em>No notes.</em>' }}</div>
      </div>
    </div>

    <div class="row row-cards mb-1 justify-content-around">
      {% comment %} Hidden rows for alignment {% endcomment %}
      <div class="col-5"></div>

      <div class="card col-3">
        <div class="card-body">
          <div class="input-group">
            <span class="input-group-text">
              <input class="form-check-input" type="checkbox" title="Confirm deletion." required/>
            </span>
            <input class="p-2 m-1 btn btn-ghost-cyan" type="submit" value="Delete!"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>

<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-1">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Date</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Ledger</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Account</div>
    </div>
    <div class="card col-4">
      <div class="card-body">Document</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Value</div>
    </div>
  </div>

  <div id="entry_rows_placeholder"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
    hx-get="{% url 'entries:hx-entry_rows' entry.id %}">
  </div>
</div>
{% endblock content %}

app/entries/templates/entries/details.html
{% extends "entries/_base.html" %}

{% block page-title %} Entry: {{ entry.id }} {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-entry" href="{% url 'entries:update' entry %}">
  <span class="nav-link-title">
    Update
  </span>
  </a>
</li>

<li class="nav-item">
  <a class="nav-link navbar-entry" href="{% url 'entries:delete' entry %}">
  <span class="nav-link-title">
    Delete
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-2">
      <div class="card-body">Journal</div>
    </div>
    <div class="card col-6">
      <div class="card-body">Notes</div>
    </div>
  </div>
  <div class="row row-cards mb-1 justify-content-around">
    <div class="card col-2">
      <div class="card-body">{{ entry.journal.id }}</div>
    </div>
    <div class="card col-6">
      <div class="card-body">{{ entry.notes | default:'<em>No notes.</em>' }}</div>
    </div>
  </div>
</div>

<div class="container mt-4">
  <div class="row row-cards mb-1 justify-content-around strong">
    <div class="card col-1">
      <div class="card-body">Entry</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Date</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Ledger</div>
    </div>
    <div class="card col-1">
      <div class="card-body">Account</div>
    </div>
    <div class="card col-4">
      <div class="card-body">Document</div>
    </div>
    <div class="card col-2">
      <div class="card-body">Value</div>
    </div>
  </div>

  <div id="entry_rows_placeholder"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
    hx-get="{% url 'entries:hx-entry_rows' entry.id %}">
  </div>
</div>
{% endblock content %}

app/entries/templates/entries/overview.html
{% extends "entries/_base.html" %}

{% load static %}

{% block page-title %} Overview of Entries {% endblock page-title %}

{% block navbar-extra %}
<div class="vr"></div>

<li class="nav-item">
  <a class="nav-link navbar-entry" href="{% url 'entries:create' %}">
  <span class="nav-link-title">
    Create
  </span>
  </a>
</li>
{% endblock navbar-extra %}

{% block content %}
<div class="container">
  <div class="row row-cards mb-1 justify-content-around">
    <div class="card col-2 strong">
      <div class="card-body">ID</div>
    </div>
    <div class="card col-2 strong">
      <div class="card-body">Journal</div>
    </div>
    <div class="card col-2 strong">
      <div class="card-body">Number of rows</div>
    </div>
    <div class="card col-5 strong">
      <div class="card-body">Notes</div>
    </div>
  </div>

  <div id="entries_list_placeholder"
    hx-get="{% url 'entries:hx-list' %}"
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML">
  </div>
</div>
{% endblock content %}